# WarriorBeat
# IOS
#
# Fastfile
# Build

import '../../fastlane/CommonFastFile'

# IOS Specific Constants
APP_ID = 'org.lamarcountyschools.ogwarriorbeat'.freeze
PROJECT_PATH = "#{IOS_PATH}/warriorbeatapp.xcodeproj".freeze
PROJECT_NAME = "warriorbeatapp".freeze
DISPLAY_NAME = "WarriorBeat".freeze

# Dev
DEV_PRODUCT = "#{DISPLAY_NAME}-dev.app".freeze
DEV_SCHEME = "#{PROJECT_NAME}-dev".freeze
DEV_BUNDLE_SUFFIX = '.dev'.freeze
DEV_ID = "#{APP_ID}#{DEV_BUNDLE_SUFFIX}"

# Staging
STAGE_PRODUCT = "#{DISPLAY_NAME}-staging.app".freeze
STAGE_SCHEME = "#{PROJECT_NAME}-staging".freeze
STAGE_BUNDLE_SUFFIX = '.staging'.freeze
STAGE_ID = "#{APP_ID}#{STAGE_BUNDLE_SUFFIX}"

# Release
RELEASE_PRODUCT = "#{DISPLAY_NAME}.app".freeze
RELEASE_SCHEME = "#{PROJECT_NAME}".freeze


# Version Constants
VERSION = get_version_number(
  xcodeproj: PROJECT_PATH,
  target: PROJECT_NAME
).freeze


default_platform(:ios)

# Set Dir to Project Root
dir = File.expand_path('../../', Dir.pwd).freeze

platform :ios do

  before_all do |lane, options|
    parsed_options = {
      :skip_before => handleEnvAndOptions(
        ENV['SKIP_BEFORE'],
        options[:skip_before],
        false,
        false
      )
    }
    
    unless parsed_options[:skip_before]
      yarn(
        command: "install",
        package_path: PACKAGE_JSON
      )
    end
  end

  desc "Update Match Certificates"
  lane :certificates do
    match(app_identifier: [DEV_ID, STAGE_ID, APP_ID])
  end

  desc "iOS Dev Build"
  lane :dev do |options|
    getEnv('dev')
    parsed_options = {
      :badge => handleEnvAndOptions(
        ENV['BADGE'],
        options[:badge],
        false,
        true
      ),
      :simulator => handleEnvAndOptions(
        ENV['SIMULATOR'],
        options[:simulator],
        false,
        false
      ),
      :clean => handleEnvAndOptions(
        ENV['CLEAN'],
        options[:clean],
        false,
        true
      ),
      :install => handleEnvAndOptions(
        ENV['INSTALL'],
        options[:install],
        false,
        false
      ),
      :xcargs => handleEnvAndOptions(
        ENV['XCARGS'],
        options[:xcargs],
        true,
        ''
      )
    }

    # Add Alpha Badge to Icon
    if parsed_options[:badge]
      add_badge(alpha:true)
    end

    # Load Dev Certs
    certificates
    match(type: 'development')

    # Build
    output_ipa = gym(
      scheme: DEV_SCHEME,
      configuration: "Debug",
      clean: parsed_options[:clean],
      xcargs: parsed_options[:xcargs],
    )

    # Install
    if parsed_options[:install]
      install_on_device(ipa: output_ipa)
    end

    sh "git checkout -- #{IOS_PATH}/warriorbeatapp/Images.xcassets/AppIcon.appiconset"
  end

  
  desc "Stage and Release on App Center"
  lane :stage do |options|
    getEnv('staging')
    parsed_options = {
      :badge => handleEnvAndOptions(
        ENV['BADGE'],
        options[:badge],
        false,
        true
      ),
      :simulator => handleEnvAndOptions(
        ENV['SIMULATOR'],
        options[:simulator],
        false,
        false
      ),
      :clean => handleEnvAndOptions(
        ENV['CLEAN'],
        options[:clean],
        false,
        true
      ),
      :install => handleEnvAndOptions(
        ENV['INSTALL'],
        options[:install],
        false,
        false
      ),
      :xcargs => handleEnvAndOptions(
        ENV['XCARGS'],
        options[:xcargs],
        true,
        ''
      ),
      :release => handleEnvAndOptions(
        ENV['RELEASE'],
        options[:release],
        false,
        false
      )
    }

    # Add Alpha Badge to Icon
    if parsed_options[:badge]
      add_badge
    end

    # Load Certs
    certificates
    match(type: 'development')

    # Inject Appcenter
    if parsed_options[:release]
      injectAppcenter('ios', APPCENTER_IOSCONFIG)
    end

    # Build
    output_ipa = gym(
      scheme: STAGE_SCHEME,
      configuration: "Staging",
      clean: parsed_options[:clean],
      xcargs: parsed_options[:xcargs],
    )

    # Install
    if parsed_options[:install]
      install_on_device(ipa: output_ipa)
    end

    # Release Appcenter
    if parsed_options[:release]
      appcenter_upload(
        should_clip: false,
        release_notes: getReleaseNotes
      )
      injectAppcenter('ios', APPCENTER_IOSCONFIG, clean:true)
    end

    # Cleanup Badges
    sh "git checkout -- #{IOS_PATH}/warriorbeatapp/Images.xcassets/AppIcon.appiconset"
  end

end
