# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import '../../fastlane/CommonFastFile'

default_platform(:android)

# Set Dir to Project Root
dir = File.expand_path('../../', Dir.pwd).freeze


platform :android do

  before_all do
    yarn(
      command: "install",
      package_path: PACKAGE_JSON
    )
  end

  desc "Runs all the tests"
  lane :test do
    getEnv('dev')
    gradle(task: "test")
  end

  desc "Build and Release on App Center"
  lane :stage do
    getEnv('stage')
    injectAppcenter("android", APPCENTER_ANDROIDCONFIG)
    gradle(task: "app:assembleRelease")
    appcenter_upload(
      apk: ENV['GRADLE_APK_OUTPUT_PATH'],
      should_clip: false,
      release_notes: getReleaseNotes
    )
    injectAppcenter("android", APPCENTER_ANDROIDCONFIG, clean:true)
  end

  desc "Install Release on Device"
  lane :install_release do
    getEnv('release')
    gradle(task: "app:assembleRelease")
    gradle(task: "app:installRelease")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
